baseURL = "https://vrops.funkycloudmedina.com/"
languageCode = "en-us"
title = "VMware Operations Guide"
theme = "hugo-theme-learn"
enableGitInfo = true

[frontmatter]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
  editURL = "https://github.com/TheNewStellW/vmware-operations-guide/tree/main/content/"

[[menu.shortcuts]] 
  name = "Iwan 'e1' Rahabok"
  identifier = "ds"
  url = "http://virtual-red-dot.info/iwan-rahabok/"
  weight = 10

[[menu.shortcuts]] 
  name = "Hosted on FunkyCloudMedina"
  identifier = "fcm"
  url = "https://www.funkycloudmedina.com/"
  weight = 15

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[markup]
    defaultMarkdownHandler = "goldmark"
	
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true